/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        xs: "420px",
        xss: "320px",
        mobile: "375px",
      },
      colors: {
        "navbar-background": "#fef7eb",
        "navbar-text": "#6d5831",
        "navbar-button-color": "#f89835",
        "navbar-button-text": "#110601",
        "hero-title": "#ffffff",
        "hero-title-highlight": "#facc13",
        "hero-button-text": "#110601",
        "hero-button-color": "#eab307",
        "form-header-background": "#f89835",
        "form-header-text": "#110601",
        "form-background": "#ffffff",
        "form-text": "#6d5831",
        "form-button-color": "#f89835",
        "form-button-text": "#110601",
        "cars-background": "#fbc999",
        "cars-text": "#000000",
        "cars-button-color": "#f89835",
        "cars-badge-color": "#fdf9c3",
        "cars-badge-text": "#b78845",
        "cars-content-background": "#fefce8",
        "about-background": "#fcdebc",
        "about-icon-background": "#fef5ee",
        "about-icon": "#f89835",
        "about-title": "#6c4e13",
        "cities-background": "#ffffff",
        "cities-text": "#111727",
        "cities-description": "#4d5764",
        "cities-button-color": "#f89835",
        "cities-button-text": "#000000",
        "cities-button-background1": "#ecebea",
        "cities-button-text1": "#232222",
        "cities-location-icon": "#f89835",
        "footer-background": "#f89835",
        "footer-text": "#000000",
      },
    },
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
